# Generated by Django 4.1.1 on 2022-11-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprint.category')),
            ],
            options={
                'verbose_name': 'Meta Tavsifilar',
            },
        ),
    ]
