# Generated by Django 4.1.1 on 2022-10-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderForm',
            new_name='Order',
        ),
    ]
