# Generated by Django 4.1.1 on 2022-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0002_type_services_lazer_price_type_services_lazer_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/service')),
            ],
            options={
                'verbose_name': 'Dizayn',
            },
        ),
        migrations.CreateModel(
            name='DigitalPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('on_site_print', models.CharField(max_length=50)),
                ('double_site_print', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/service')),
            ],
            options={
                'verbose_name': 'Raqamli chop etish',
            },
        ),
        migrations.CreateModel(
            name='LargeFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('product_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/service')),
            ],
            options={
                'verbose_name': 'Katta formatda chop etish',
            },
        ),
        migrations.CreateModel(
            name='LaserPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('size', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='media/service')),
            ],
            options={
                'verbose_name': 'Lazerni chop etish',
            },
        ),
        migrations.CreateModel(
            name='TextPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('size', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='media/service')),
            ],
            options={
                'verbose_name': 'Tekstilni chop etish',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': "Xizmat ko'rsatish rasmlari"},
        ),
        migrations.RemoveField(
            model_name='type',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(default=2, max_length=65),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type_Services',
        ),
    ]
