# Generated by Django 4.1.1 on 2022-10-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0003_alter_order_vat_alter_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_uz',
        ),
    ]
