# Generated by Django 4.1.1 on 2022-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0003_designe_digitalprint_largeformat_laserprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalprint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='largeformat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laserprint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textprint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
