# Generated by Django 4.1.1 on 2022-10-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0004_alter_designe_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='designe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='digitalprint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='digitalprint',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='largeformat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='largeformat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='laserprint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laserprint',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='textprint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='textprint',
            name='slug',
        ),
    ]
